from playwright.sync_api import sync_playwright

def run():
    with sync_playwright() as p:
        browser = p.chromium.launch()
        page = browser.new_page()

        # 1. Homepage
        print("Navigating to Home...")
        page.goto("http://localhost:8080")
        page.screenshot(path="verification/1_home.png", full_page=True)

        # 2. Products (All Categories + Featured)
        print("Navigating to Products...")
        page.goto("http://localhost:8080/products")
        page.screenshot(path="verification/2_products_all.png", full_page=True)

        # 3. Category View (e.g., Specjalne)
        print("Navigating to Category 'Specjalne'...")
        page.goto("http://localhost:8080/products?category=specjalne")
        page.screenshot(path="verification/3_category_specjalne.png", full_page=True)

        # 4. Product Detail (Super Fat) - we need to find its ID first or assume one.
        # Let's click on the "Więcej informacji" link for Super Fat from the category page.
        print("Navigating to Super Fat product page...")
        # Finding the link for Super Fat
        # Assuming "SUPER FAT" is the name.
        # We can look for the text "SUPER FAT" and find the closest link.
        # Or just look for the link that contains "SUPER FAT" inside the card.

        # Since I don't know the exact ID generated by the DB (auto-increment), I'll click the link.
        # The text in the card title is "SUPER FAT"

        # Find the card that has "SUPER FAT"
        # Then find the "Więcej informacji" link within that card container.
        # However, simple approach: Click the first product in the "Specjalne" category which should be Super Fat or similar.

        # Let's try to click the link for "SUPER FAT" if we can target it.
        # The structure is h3 -> text.

        # Let's just grab the first link to a product details page from this category view
        with page.expect_navigation():
            page.locator(".grid a[href^='/product/']").first.click()

        page.screenshot(path="verification/4_product_detail.png", full_page=True)

        browser.close()
        print("Verification screenshots captured.")

if __name__ == "__main__":
    run()
